//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HpLogger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>f +2.345 3.5</string>
  <string>d +2.345 3.5</string>
  <string>e +2.345 3.5</string>
  <string>g +2.345 3.5</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BEV1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BEV1"]));
            }
            set {
                this["BEV1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>d -2.345 3.5</string>
  <string>e -2.345 3.5</string>
  <string>g +2.345 3.5</string>
  <string>f -2.345 3.5</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BEV2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BEV2"]));
            }
            set {
                this["BEV2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>d 0 12</string>
  <string>e 0 12</string>
  <string>f 0 12</string>
  <string>g 0 12</string>
  <string>h 0 12</string>
  <string>i 0 12</string>
  <string>j 0 12</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CCL {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CCL"]));
            }
            set {
                this["CCL"] = value;
            }
        }
    }
}
